select * from customers;
select * from Orders;

/**
1. Write a query to display the custid ,name, age, orderid,orderdate for 
product books or cd, sort data by name in descending order
*/

select c.custid,c.custname,c.age,o.orderid,o.product,o.orderdate from customers as c
join Orders as o
on c.custid=o.custid
where o.product in ('Notebook','mouse')
order by c.custname desc;


/**
2. Write a SQL statement to find the list of customers who live in the 
same city as pooja, and display custid , custname , price (price > 500)
**/

select c.custid,c.custname,o.price as [price(price>500)] from customers as c
join Orders as o
on c.custid=o.custid
where o.price>500 and caddress in(select caddress from customers where custname='pooja');

/**
3. Write a query to find the name of customers along with order details 
who purchased   more than two products 
**/

select c.custname,o.* from customers as c
join Orders as o
on
c.custid=o.custid
where o.qty>2;

/**
4. A discount of 20% has been announced to all customers who resides 
in Bangalore . display custid , custname , orderid  and discount price  
**/

select c.custid,c.custname,o.orderid,(o.price-o.price*0.20) as [Discount Price] from customers as c
join Orders as o
on
c.custid=o.custid
where c.caddress='Bangalore';

-- 5. write a query to join three tables (create products table for the same) 

create table Products
(
productid int,
custid int,
product varchar(20)
);

insert into Products values
(1,1,'Notebook'),
(2,2,'Pen Set'),
(3,3,'USB Cable'),
(4,4,'Mouse'),
(5,5,'Keyboard'),
(6,6,'Pen Set'),
(7,7,'Notebook');

select * from customers;
select * from Orders;
select * from Products;

select * from customers as c
join Orders as o
on
c.custid=o.custid
join Products as p
on
o.custid=p.custid;

/**
6. update price by 5% from orders table for customers who resides in 
pune and chennai
**/

select * from Orders;
select * from customers;

update Orders 
set price= price+price*0.05 
where price in (select o.price  from Orders as o
join customers as c
on
c.custid=o.custid
where c.caddress in ('Lucknow','chennai'));

/**
7. create a report in following format 
 
Custidord Custname Product Price orderdate 
cid:100-ordid:1          
  
1. Custname should be uppercase 
2. Display only first 3 character of product 
3.  The report should be of December 2025
**/

select * from Orders;
select * from customers;

select concat('cid:',c.custid,'-','ordid:',o.orderid) as Custidord,
upper(c.custname) as Custname,left(o.product,3) as Product,o.price,o.orderdate from customers as c
join Orders as o
on
c.custid=o.custid
where month(o.orderdate)=12 and year(o.orderdate)=2025;

---- Validation-------------------------------------------------------------------------------

/**
Create Table Students 
 
StudentRollNumber 
StudentName 
DOB 
Class 
 
1. Student Roll Number should be  autogenerated as (100,200,300…). 
Alter Command 
a. DOB cannot be greater then current date 
b. Class should be between 1 - 10

**/

create table Students
(
StudentRollNumber int identity(100,1) constraint Sidpk primary key,
StudentName varchar(20),
DOB varchar(20),
Class int
)

select * from Students;

-- alter command
-- a. DOB cannot be greater then current date 

alter table Students
add
Constraint check_DOB
check (DOB < getdate());

-- b. Class should be between 1 - 10

alter table Students
add
Constraint check_Class
check (Class between 1 and 10);

insert into Students values 
('Ram','2000-11-23',2),
('Shayam','2002-06-16',5);

select * from Students;

/**
Create Table Stock 
StockId 
MinStockLvl 
MaxStockLvl 
 
Alter Command 
The MaxStockLvl should be Greater than MinStockLvl. 
Stock id should be following format 
stc-11-aaa 
Start with 3 alphabets following by – followed by 2 digit followed by – and 
ending with 3 alphabets .
**/

create table Stock
(
StockId int ,
MinStockLvl float(2),
MaxStockLvl float(2)
);

select * from Stock;

-------------- Alter command ----------------------

-- The MaxStockLvl should be Greater than MinStockLvl. 

alter table Stock
add constraint ckeck_Level
check(MaxStockLvl>MinStockLvl);

-- Stock id should be following format 
-- stc-11-aaa 

alter table Stock
add FormatStockid as ('stc-'+right('00'+cast(StockId as varchar(2)),2)+'-aaa');


insert into Stock values(11,1000,2000);

select * from Stock;

/**
Create Table purchase 
 
Productid 
PurchaseDate 
Serialno 
Price 
Qty  
Total 
 
• The default value for purchase date should be the system date. 
• Serialno  should be a unique  
• Total to be autogenerated 
• Create a rule  qty should be greater than 1 
• Create a rule where price should be between 1000 and  7000 
**/

create table purchase
(
productid int Constraint Pkpid primary key,
purchaseDate date default getdate(),
Serialno int unique,
Price decimal(10,2) check(Price between 1000 and 7000),
qty int check (qty>1),
Total as (Price*qty)
);


insert into purchase (productid,serialno,price,qty)values
(3,1003,1000,2);

select * from purchase;

